.gitignore, hunger/composer.lock, hunger/index.php
=> Added Caching for the hunger page

redirect/routes.php
This will make the router use normal PHP arrays which can be cached by PHP itself and reduces the overhead in finding the routes.
=> Properly implement the router

redirect/routes.php
Added a link to a website for my tutorial. :)
And added a link to Carlos Camino's website.
Haven't run it though. I'm guessing it works.
=> Added Two Links

redirect/routes.php
=> Changes Asked Done!

.htaccess
Not sure if this works
Could you try this out?
This should make Apache handle all the URL rewriting without sending 302 Found to the browser.
This might even make tum.sexy faster (as there is only one request to do)
=> Handle URL rewriting internally

redirect/routes.php
=> Changed Analysis Semester, EIDI2

hunger/index.php
improve regex matching as discussed in mammuth/TUM.sexy#25
=> [HUNGER] Improve Regex

redirect/routes.php
I'm teaching another tutorial so to make a site for all I'm changing the redirect...
=> Updating Website Name

redirect/routes.php
DS, ERA and Info1 for the freshmen :heart:
=> add stuff for 1. Semester

redirect/routes.php
GBS dieses Semester vom IT SEC Lehrstuhl
=> New shortcut for GBS

index.php, opensearchdescription.xml
haven't tested it, but a problem should just show up in the dev console
=> addition of opensearchdescription document

index.php
Added Link to Ersti Tipps Google Doc (you can save a copy of the doc on tum.sexy if you want to)
=> Added Ersti Tipps

tpl/head.twig
=> Fix css includes for /hunger

redirect/routes.php
Numprog link was for last semester
=> Updated numprog.tum.sexy

redirect/routes.php
Added redirect for "Practical Course: Algorithms for Programming Contests"
=> Updated routes.php with 'conpra'

redirect/routes.php
- Corrects a ü
- Add another telegram mensa bot (and also to a section)
=> Add yet another telegram bot

composer.json, composer.lock, hunger/index.php, tpl/hunger.twig
Follow-up for #67 
The PDF structure isn't really consistent so far. So for the new semester I think we should just display the link for now.
To render the PDF, I'd use https://github.com/spatie/pdf-to-image, which requires the PHP extension imagick. I'm not sure if this would work out of the box or if someone with access to the server would need to install it.
=> Update hunger for the new bistro

redirect/routes.php
I created a new section called "Electives" which contains all those non-mandatory courses.
Also fixes some indentation errors.
Didn't test it, just hope it works 🙈 I didn't bother setting up that php tooling locally.
Related issue: #78
=> Add electives to page

.gitmodules, .travis.yml, composer.json, composer.lock, phpunit.xml, tests/General/MainTest.php, tests/bootstrap.php
=> #82 add unit testing for the router

redirect/routes.php
hopefully no missing commas this time
=> add Geokalküle, added EIDI synonyms

css/custom.css, css/skeleton.css, js/staticsearch.js, tpl/start.twig
Resolves #81 
Imported staticsearch.js
Updated the html and css to add a search input box
Updated the css to use flexbox rendering on columns due to issues with hidden elements
=> Implemented search box

.travis.yml, composer.json, hunger/index.php, tpl/hunger.twig, tpl/hunger_menu.twig
=> Add Support for FMI Bistro „Wilhelm Gastronomie“ and Mensa Garching

redirect/routes.php
Links to our uni's cool satellite!
https://www.move2space.de/
=> Add sexy links to the TUM satellite.

redirect/routes.php
Site seems to be offline:
https://tumeme.alpheca.uberspace.de/
=> Remove tumeme.tum.sexy

.htaccess, index.php, js/cats.js, tpl/body.twig, tpl/start.twig
=> Pretty urls

redirect/routes.php
Updating numprog url in routes.php
=> Updating numprog url in routes.php

Dockerfile
=> Install apcu with pecl

redirect/routes.php
Added lecture of Berthold Baeuml.
=> Added "Advanced Deep Learning for Robotics"

redirect/routes.php
Also added this to the frontpage list for 4th semester as this might be interesting for a few more people
=> Add theo tumjudge url

redirect/routes.php
Redirects for the lectures of chair XXII (Prof. Albu-Schäffer)
- Sensor-based Robotic Manipulation and Locomotion (IN2068)
- Robot Programming and Control for Human Interaction (IN2308)
=> Add redirects for SBRML and RPCHI lectures

redirect/routes.php
=> Close #140

hunger/index.php
Hot fixes #145
We should revert this change after jpbernius/FMeat.php#4 is fixed.
=> Disable STUCAFE_BOLTZMANNSTRASSE until Problem is resolved

redirect/routes.php
The CSC lecture is offered in the winter term 2018/2019 again. Here is the new link.
=> Updated CSC link

hunger/index.php
Better fix for #145, as this occurred again, this time with the Mensa Menu.
We still need a proper fix of the root cause jpbernius/FMeat.php#4.
This reverts #146 in favour of error handling of the Type Error.
=> Catch TypeError on Hunger

tpl/hunger.twig
useful because it is not always opened and has changing menu
should be enriched with more information, just a first version
=> add pita booth entry to hunger

Dockerfile
https://twitter.com/php_net/status/1010263293330632705?s=21
=> Update PHP to 7.2.7

redirect/routes.php
Wouldn't it be a good idea to add the Studienplan for Games Engineering aswell?
=> Add Games Engineering Studienplan

redirect/routes.php
For more about ESN or TUMi checkout: 
- http://www.international.tum.de/tumi/
- https://www.esn-germany.de/
=> Add esn redirect

redirect/routes.php
There is a new poetry slam coming up. Need the new URL plz :+1:
=> Update Slam URL

redirect/routes.php
Update Eidi2-URL, move to http as certifacte is invalid, remove moodle course id as it still unknown.
=> EIDI2 - WS18/19

redirect/routes.php
I've removed the cname to the github page and would love to redirect it to facebook instead
=> Add TUM pride

redirect/routes.php
=> new ERA moodle course

redirect/routes.php
added Signaldarstellung and updated Analysis moodle course
=> Signaldarstellung and Analysis

redirect/routes.php
The name says it all.
Closes #128
=> Sort electives by name

redirect/routes.php
This adds Program Optimization, Advanced Algorithms, Efficient Algorithms and Algebra 1 and updates the NumProg and Anal links (both of them don't have a proper website anymore and only use Moodle).
Btw I also noticed that the auto update doesn't seem to be working as for example the update from #180 still isn't live. <info1.tum.sexy> still points to the website from last year.
=> Add more electives and update numprog and anal

redirect/routes.php
Changed ERA-Praktikum to current (Wintersemester 18/19) website
=> Changed ERA-Praktikum to Wintersemester

tpl/hunger/hunger.twig, tpl/hunger/menu.twig
In some places (like MI bistro) there are fixed specials every week. This pr adds these to the regular weekly meal list.
=> hunger: add fixed dishes

redirect/routes.php
Updated eist link for summer 2019
=> Update eist link

redirect/routes.php
Updated redirects for GAD and ERA-Praktikum
gadjudge redirects to TUMjudge course for GAD
=> Updated redirects + Added gadjudge

redirect/routes.php
https://www21.in.tum.de/teaching/theo/SS19/
=> New link for Theo (IN0011)

redirect/routes.php
Added the ilab practical courses as links
=> added ilab practical courses

redirect/routes.php
updated ge-sp to the newest version
updated ged to the newest version
added sp-ge alias for ge-sp
=> Updated outdated links

redirect/routes.php
Added future.tum.sexy -> tum4future.de
=> future.tum.sexy -> tum4future.de

redirect/routes.php
Fixing the redirect to tu film and adding it to the special section
=> fix tu film link

tpl/hunger/hunger.twig
I just stumbled across this using the English homepage (I don't see if there is a German version) and thought this might be a appropriate small fix.
=> Update header according to additional available information

redirect/routes.php, tests/General/MainTest.php
Please note: In case someone's checking the Moodle course ID I've added, this ID is valid, the course just isn't public yet.
=> Update GBS for WiSe 2019/2020

redirect/routes.php
Add a shortcut for Think. Make. Start.
=> add thinkmakestart to routes

.travis.yml, Dockerfile, composer.json, composer.lock, tests/General/MainTest.php
- php 7.3
- phpunit 8.2
- fmeat.php 2.0
=> Update PHP Version and Dependencies

redirect/routes.php
The new DS website for the winter semester 2019/2020 is online.
=> Updated link for "Diskrete Strukturen"

redirect/routes.php
Added finder.tum.sexy and roomfinder.tum.sexy as shortcuts for the physics department roomfinder at https://www.ph.tum.de/about/visit/roomfinder/
=> Added finder.tum.sexy for the roomfinder

redirect/routes.php
=> SET der FSMPI

js/cats.js
=> HTTPS Cats

redirect/routes.php
Previous id referred to moodle course of 18/19
=> Updated moodle id for 19/20 "Analysis für Informatik"

redirect/routes.php
Aspekte der systemnahen Programmierung bei der Spieleentwicklung for Games Engineering
=> Add asp redirect 

redirect/routes.php
Changed subdomain to fpv; info2 and eidi2 are aliases
Updated moodle id and link to lecture page
=> Updated link to Functional Programming and Verification

redirect/routes.php
added Künstlicher Intelligenz, Medizin 1, Patterns; updated NumProg to WS2019; added synonyms for ki, fpv, pat; added pat, ki to electives section; adjusted spacing in synonyms array;
=> updated / added several links; spacing adjustment in synonyms array

redirect/routes.php
=> updated ADM, ITSec, Automata  added "selected ITSec"

tpl/start.twig
Since You brought the sexypretschi game back to life I thought it would be cool to link it on the homepage as well
=> Update sexypretschi URL

redirect/routes.php
Adds shortcuts to TUM shibboleth login pages of IEEE Xplore and Springer link.
=> Add IEEE Xplore and Springer Link login links

redirect/routes.php
https://learngitbranching.js.org is a nice plattform to learn git. Could be handy for starters.
=> New Route for Git-starters

redirect/routes.php
Add a redirect to the eAccess login page for Scopus.
=> Add redirect to scopus eAccess login

redirect/routes.php
Updated routing for Advanced Deep Learning for Robotics for SS20
=> Updated routing for ADLR

redirect/routes.php
Just added a new route for the current semester.
=> Added Automatatutor link for Theo

.github/workflows/branches.yml, .github/workflows/master.yml, Dockerfile, composer.json
=> Add github actions support

redirect/routes.php
old route isn't working anymore
=> updated dwt route

redirect/routes.php
Adds a redirect to the moodle page of "Medizin 2"
(I recreated this pull request because I forgot to properly sync the fork)
=> Add med2 redirect

redirect/routes.php
GAD uses Artemis now instead of TUMjudge
=> Remove gadjudge

redirect/routes.php
- Added Walomat 
- Updated sv.tum.de/wahl
- Added Synonyms for Walomat and Wahl
=> Add HSW Routes

redirect/routes.php
My own website, which a few students used for GAD/PGdP and for the "Eidi-Repititorium". I just figured it'd be funny, if it was linked on tum.sexy. I also quite enjoy the sound of "julius.tum.sexy", if ya know what I mean 🐧
=> added julius-kreutz.de website
